import "./globals.css";

import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import type { ReactNode } from "react";

import { Toaster } from "@/components/ui/Toaster";
import { intl } from "@/i18n/server";
import { cn } from "@/lib/tailwind";

import { Footer } from "./_components/Footer";
import { Header } from "./_components/Header";
import { ThemeScript } from "./_scripts/theme";
import { Providers } from "./providers";

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin", "cyrillic"],
});

export const metadata: Metadata = {
  title: "JB market",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html
      suppressHydrationWarning
      lang={intl.locale}
      className={cn(nunito.variable)}
      data-scroll-behavior="smooth"
    >
      <head>
        <ThemeScript />
      </head>
      <body className="flex min-h-screen flex-col overflow-x-hidden">
        <Providers intl={{ locale: intl.locale, messages: intl.messages }}>
          <div className="content-container">
            <Header />
            <div className="flex flex-1 flex-col">{children}</div>
            <Footer />
          </div>
        </Providers>
        <Toaster />
      </body>
    </html>
  );
}
