import "./globals.css";

import type { Metadata } from "next";
import type { ReactNode } from "react";

import { Toaster } from "@/components/ui/toaster";
import { intl } from "@/i18n/server";

import { Header } from "./_components/Header";
import { ThemeScript } from "./_scripts/theme";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "JB market",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html suppressHydrationWarning lang={intl.locale}>
      <head>
        <ThemeScript />
      </head>
      <body className="flex min-h-screen flex-col overflow-x-hidden">
        <Providers intl={{ locale: intl.locale, messages: intl.messages }}>
          <div className="content-container">
            <Header />
            <div className="flex flex-1 flex-col">{children}</div>
          </div>
        </Providers>
        <Toaster />
      </body>
    </html>
  );
}
