import "./globals.css";

import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import type { ReactNode } from "react";

import { getUserProfile } from "@/api/handlers/users/profile";
import { Toaster } from "@/components/ui/Toaster";
import { intl } from "@/i18n/server";
import { cn } from "@/lib/tailwind";

import { ThemeScript } from "./_scripts/theme";
import { Providers } from "./providers";

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin", "cyrillic"],
});

export const metadata: Metadata = {
  title: "JB market",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

export default async function RootLayout({ children }: RootLayoutProps) {
  const userProfileResponse = await getUserProfile().catch(() => null);
  const user = userProfileResponse?.data.user ?? null;

  return (
    <html
      suppressHydrationWarning
      lang={intl.locale}
      className={cn(nunito.variable)}
      data-scroll-behavior="smooth"
    >
      <head>
        <ThemeScript />
      </head>
      <body className="flex min-h-screen flex-col overflow-x-hidden">
        <Providers
          intl={{ locale: intl.locale, messages: intl.messages }}
          user={user}
        >
          <div className="content-container">{children}</div>
        </Providers>
        <Toaster />
      </body>
    </html>
  );
}
